package com.spring2020cyse6225.studinfo.awsDataSchema;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

public class Announcement {

    /*
    Announcements
     - Id (Dynamo Db generated) and hash key
     - announcementId - dynamodb Index range key part of the GSI
     - announcementText - (ensure text size is no more than 160 characters)
     - boardId -DynamoDbIndexHashKey, part of the GSI Global Secondary Index (GSI)
     */

//    private Long Id;

    private Long announcementId;

    private String announcementText;

    private Long boardId;

    public Announcement() {
    }

    public Announcement(/*Long id,*/
                        Long announcementId,
                        String announcementText,
                        Long boardId) {
//        Id = id;
        this.announcementId = announcementId;
        this.announcementText = announcementText;
        this.boardId = boardId;
    }

    /*
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public Long getId() {
        return Id;
    }
    public void setId(Long id) {
        Id = id;
    }
     */

    @DynamoDBHashKey(attributeName = "announcementId")
    public Long getAnnouncementId() {
        return announcementId;
    }
    public void setAnnouncementId(Long announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName = "announcementText")
    public String getAnnouncementText() {
        return announcementText;
    }
    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public Long getBoardId() {
        return boardId;
    }
    public void setBoardId(Long boardId) {
        this.boardId = boardId;
    }

    @Override
    public String toString() {
        return "Announcement{" +
                "announcementId=" + announcementId +
                ", announcementText='" + announcementText + '\'' +
                ", boardId=" + boardId +
                '}';
    }
}
