package com.spring2020cyse6225.studinfo.awsDataSchema;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

public class Board {

    /*
    Board
     - Id (Dynamo Db generated) and hash key
     - boardId - DynamoDbIndexHashKey, a Global Secondary Index (GSI)
     - courseId
     */

//    private Long Id;

    private Long boardId;

    private Long courseId;

    public Board() {
    }

    public Board(/* Long id, */ Long boardId, Long courseId) {
//        Id = id;
        this.boardId = boardId;
        this.courseId = courseId;
    }

    /*
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public Long getId() {
        return Id;
    }
    public void setId(Long id) {
        Id = id;
    }
     */

    @DynamoDBHashKey(attributeName = "boardId")
    public Long getBoardId() {
        return boardId;
    }
    public void setBoardId(Long boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public Long getCourseId() {
        return courseId;
    }
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }
}
