package com.spring2020cyse6225.studinfo.awsDataSchema;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import java.util.Date;
import java.util.Set;

public class Student {

    /*
    Student
     - Id (Dynamo Db generated) and hash key
     - studentId - DynamoDbIndexHashKey, a Global Secondary Index (GSI)
     - firstName
     - lastName
     - joiningDate
     - department
     - registeredCourses - has list of registered courseIds
    */

//    private Long Id;

    private Long studentId;

    private String firstName;

    private String lastName;

    private Date joinDate;

    private String department;

    private Set<Object> registeredCourses;

    public Student() {
    }

    public Student(/* Long id, */
                   Long studentId,
                   String firstName,
                   String lastName,
                   Date joinDate,
                   String department,
                   Set<Object> registeredCourses) {
//        Id = id;
        this.studentId = studentId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.joinDate = joinDate;
        this.department = department;
        this.registeredCourses = registeredCourses;
    }

/*
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public Long getId() {
        return Id;
    }
    public void setId(Long id) {
        Id = id;
    }
 */

    @DynamoDBHashKey(attributeName = "studentId")
    public Long getStudentId() {
        return studentId;
    }
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "joinDate")
    public Date getJoinDate() {
        return joinDate;
    }
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }
    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "registeredCourses")
    public Set<Object> getRegisteredCourses() {
        return registeredCourses;
    }
    public void setRegisteredCourses(Set<Object> registeredCourses) {
        this.registeredCourses = registeredCourses;
    }
}
